// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Desc: typeof import('./../.vitepress/theme/components/Desc.vue')['default']
    Home: typeof import('./../.vitepress/theme/components/Home.vue')['default']
    Test: typeof import('./../.vitepress/theme/components/Test.vue')['default']
    VpDemo: typeof import('./../.vitepress/theme/components/vp-demo.vue')['default']
  }
}
